# Type stubs for fast_litellm

from typing import Any

# Constants
RUST_ACCELERATION_AVAILABLE: bool
__version__: str

# Core functions
def apply_acceleration() -> bool: ...
def remove_acceleration() -> None: ...
def health_check() -> dict[str, Any]: ...

# Feature flag functions
def is_enabled(feature_name: str, request_id: str | None = None) -> bool: ...
def get_feature_status() -> dict[str, Any]: ...
def reset_errors(feature_name: str | None = None) -> None: ...

# Performance monitoring functions
def record_performance(
    component: str,
    operation: str,
    duration_ms: float,
    success: bool = True,
    input_size: int | None = None,
    output_size: int | None = None,
    metadata: dict[str, Any] | None = None,
) -> None: ...
def get_performance_stats(component: str | None = None) -> dict[str, Any]: ...
def compare_implementations(
    rust_component: str, python_component: str
) -> dict[str, Any]: ...
def get_recommendations() -> list[dict[str, Any]]: ...
def export_performance_data(
    component: str | None = None, format: str = "json"
) -> str: ...
def get_patch_status() -> dict[str, Any]: ...
